import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { apiFetch, authEnabled, currentRoles, keycloak } from './auth';
import { IdentityUsersPage } from './IdentityUsersPage';

type Student={id:string;admissionNo:string;firstName:string;lastName?:string;dateOfBirth?:string;fatherName:string;contactNumber:string;aadhaarNumber?:string;samagraId?:string;address:string;status:string};
type Form={firstName:string;lastName:string;dateOfBirth:string;fatherName:string;contactNumber:string;aadhaarNumber:string;samagraId:string;address:string};
type View='admissions'|'directory'|'users';
const blank:Form={firstName:'',lastName:'',dateOfBirth:'',fatherName:'',contactNumber:'',aadhaarNumber:'',samagraId:'',address:''};

function App(){
  const[auth,setAuth]=useState<'loading'|'ready'|'login'|'error'>('loading');const[students,setStudents]=useState<Student[]>([]);const[form,setForm]=useState<Form>(blank);const[editing,setEditing]=useState<Student|null>(null);const[view,setView]=useState<View>('admissions');const[query,setQuery]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');
  useEffect(()=>{if(!authEnabled){setAuth('ready');return;}keycloak.init({onLoad:'check-sso',pkceMethod:'S256',checkLoginIframe:false}).then(ok=>setAuth(ok?'ready':'login')).catch(()=>setAuth('error'));},[]);
  const load=async()=>{try{const r=await apiFetch('/api/v1/students');if(!r.ok)throw Error(`Student Service returned HTTP ${r.status}.`);setStudents(await r.json());}catch(e){setError(e instanceof Error?e.message:'Unable to reach the Student Service.');}};
  useEffect(()=>{if(auth==='ready')void load();},[auth]);
  const shown=useMemo(()=>students.filter(s=>`${s.admissionNo} ${s.firstName} ${s.lastName??''} ${s.fatherName} ${s.contactNumber}`.toLowerCase().includes(query.toLowerCase())),[students,query]);
  const change=(key:keyof Form,value:string)=>setForm(current=>({...current,[key]:value}));
  const reset=()=>{setForm(blank);setEditing(null);setError('');setNotice('');};
  const edit=(s:Student)=>{setEditing(s);setForm({firstName:s.firstName,lastName:s.lastName??'',dateOfBirth:s.dateOfBirth??'',fatherName:s.fatherName??'',contactNumber:s.contactNumber??'',aadhaarNumber:s.aadhaarNumber??'',samagraId:s.samagraId??'',address:s.address??''});setView('admissions');setError('');setNotice(`Editing admission number ${s.admissionNo}.`);};
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{const r=await apiFetch(editing?`/api/v1/students/${editing.id}`:'/api/v1/students',{method:editing?'PUT':'POST',body:JSON.stringify(form)});const body=await r.json().catch(()=>null);if(!r.ok)throw Error(body?.message??'Could not save admission.');const created=!editing;reset();setNotice(created?`Student admitted successfully. Admission number: ${body.admissionNo}`:'Admission record updated successfully.');await load();}catch(x){setError(x instanceof Error?x.message:'Could not save admission.');}};
  const remove=async(s:Student)=>{if(!confirm(`Delete ${s.firstName} ${s.lastName??''}'s admission record?`))return;try{const r=await apiFetch(`/api/v1/students/${s.id}`,{method:'DELETE'});if(!r.ok)throw Error(`Could not delete this record (HTTP ${r.status}).`);setNotice('Admission record deleted.');await load();}catch(x){setError(x instanceof Error?x.message:'Could not delete this record.');}};
  if(auth==='loading')return <Landing text="Loading school portal…"/>;if(auth==='login')return <Login/>;if(auth==='error')return <Landing text="Keycloak could not be reached. Check frontend configuration."/>;
  const canManageUsers=!authEnabled||currentRoles().includes('SCHOOL_ADMIN')||currentRoles().includes('PRINCIPAL');
  return <div className="app-shell"><aside><div className="brand"><span>SP</span><div><strong>Sarbottam Pragati</strong><small>Vidya Peeth</small></div></div><nav><Nav label="Admissions" active={view==='admissions'} click={()=>setView('admissions')}/><Nav label="Student Directory" active={view==='directory'} click={()=>setView('directory')}/>{canManageUsers&&<Nav label="User Management" active={view==='users'} click={()=>setView('users')}/>}<a>Attendance</a><a>Fees</a></nav><footer>{authEnabled&&<button className="logout" onClick={()=>keycloak.logout({redirectUri:window.location.origin})}>Log out</button>}<br/>SARBOTTAM PRAGATI<br/><strong>VIDYA PEETH</strong></footer></aside><main>{view==='users'?<IdentityUsersPage/>:view==='directory'?<Directory students={shown} query={query} setQuery={setQuery} edit={edit} remove={remove}/>:<Admission form={form} editing={editing} change={change} reset={reset} submit={submit}/>} {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}</main></div>;
}

function Nav({label,active,click}:{label:string;active:boolean;click:()=>void}){return <a className={active?'active':''} onClick={click}>{label}</a>}
function Login(){return <div className="login-page"><div className="login-card"><span className="login-mark">SP</span><p className="eyebrow">SARBOTTAM PRAGATI VIDYA PEETH</p><h1>School portal</h1><p className="subheading">Sign in with your authorised school account.</p><button onClick={()=>keycloak.login({redirectUri:window.location.origin})}>Log in securely <span>→</span></button></div></div>}
function Landing({text}:{text:string}){return <div className="login-page"><div className="login-card"><span className="login-mark">SP</span><h1>School portal</h1><p className="subheading">{text}</p></div></div>}
function Admission({form,editing,change,reset,submit}:{form:Form;editing:Student|null;change:(k:keyof Form,v:string)=>void;reset:()=>void;submit:(e:FormEvent)=>void}){return <><Header title={editing?'Edit student admission':'Student admission form'} sub={editing?'The admission number is permanent and cannot be changed.':'The admission number will be generated automatically when you save.'}/><section className="card form-card"><div className="card-title"><div><h2>Admission details</h2><p>Fields marked <b>*</b> are mandatory.</p></div>{editing&&<span className="editing-badge">{editing.admissionNo}</span>}</div><form onSubmit={submit}><p className="form-section">Student information</p><div className="form-grid"><Field label="First name *" value={form.firstName} change={v=>change('firstName',v)} required/><Field label="Last name" value={form.lastName} change={v=>change('lastName',v)}/><Field label="Date of birth" value={form.dateOfBirth} change={v=>change('dateOfBirth',v)} type="date"/></div><p className="form-section">Parent and contact information</p><div className="form-grid"><Field label="Father's name *" value={form.fatherName} change={v=>change('fatherName',v)} required/><Field label="Contact number *" value={form.contactNumber} change={v=>change('contactNumber',v)} required/><Field label="Aadhaar number" value={form.aadhaarNumber} change={v=>change('aadhaarNumber',v.replace(/\D/g,'').slice(0,12))}/><Field label="Samagra ID" value={form.samagraId} change={v=>change('samagraId',v)}/></div><label className="full-field">Residential address *<textarea required value={form.address} onChange={e=>change('address',e.target.value)}/></label><div className="actions"><button type="button" className="ghost" onClick={reset}>Cancel</button><button type="submit">{editing?'Save changes':'Create admission'} <span>→</span></button></div></form></section></>}
function Directory({students,query,setQuery,edit,remove}:{students:Student[];query:string;setQuery:(x:string)=>void;edit:(s:Student)=>void;remove:(s:Student)=>void}){return <><Header title="Student directory" sub="View, find, edit, and manage every admission record."/><section className="card directory"><div className="directory-head"><div><h2>All admission records</h2><p>{students.length} matching record(s)</p></div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, father, phone or admission no."/></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Admission no.</th><th>Father / contact</th><th>Status</th><th/></tr></thead><tbody>{students.length===0?<tr><td colSpan={5} className="empty">No admission records match your search.</td></tr>:students.map(s=><tr key={s.id}><td><div className="student-cell"><span className="avatar">{s.firstName[0]}{s.lastName?.[0]??''}</span><strong>{s.firstName} {s.lastName}</strong></div></td><td>{s.admissionNo}</td><td><strong>{s.fatherName}</strong><small className="phone">{s.contactNumber}</small></td><td><span className="status">{s.status}</span></td><td className="row-actions"><button onClick={()=>edit(s)}>Edit</button><button className="delete" onClick={()=>remove(s)}>Delete</button></td></tr>)}</tbody></table></div></section></>}
function Header({title,sub}:{title:string;sub:string}){return <header><div><p className="eyebrow">SARBOTTAM PRAGATI VIDYA PEETH</p><h1>{title}</h1><p className="subheading">{sub}</p></div></header>}
function Field({label,value,change,required,type='text'}:{label:string;value:string;change:(v:string)=>void;required?:boolean;type?:string}){return <label>{label}<input type={type} required={required} value={value} onChange={e=>change(e.target.value)}/></label>}
createRoot(document.getElementById('root')!).render(<App/>);
